### PR TITLE
Feature/ssh creds

### PR DESCRIPTION
**Pull request by terabyte**
WIP.

### CODE REVIEW

**Comment by alexander-87** [comment]
Hi @terabyte, I noticed there's an open PR for SSH support ([#6](https://github.com/palantir/stashbot/pull/6)) in the original repo too, but it seems to have stagnated over the past year.

Just curious - is your intention to have this PR supersede the other one?

> **P.S.** _Thanks for the awesome plugin!_ :+1:

**Comment by terabyte** [comment]
@alexander-87 yeah, it is my intent to have this PR supersede that one.  I want stashbot to remain a "drop in, just-works" type solution, so that means not requiring people to deploy SSH keys - but it also means not requiring installing old, broken versions of the jenkins git and git-client plugin (which is currently necessary to make username/pw work - http auth is broken in modern jenkins, the way stashbot does it).  Also, many organizations use a self-signed CA cert for stash, which adds additional complexity to stashbot setup of jenkins.  Finally, http protocol has some race conditions in it (https://jira.atlassian.com/browse/STASH-6887) so there are really many reasons to switch to using ssh protocol if I can make it work nicely.

I am _super_ glad you like the plugin, and the feedback I've gotten so far has been really positive so I hope I get to continue working on it =)

-Carl

**Comment by alexander-87** [comment]
Hi Carl, I'm more than happy to try out a beta version once you've got something ready. I'm currently running Stash `v3.9.1` and Jenkins `v1.617`.

Also, please correct me if I'm wrong, but it looks like we're still going to need a dedicated Stash user for Jenkins to use when pulling down the repo, right?

If so, I'd love to be able to use the [Access Keys feature](https://confluence.atlassian.com/display/STASH039/SSH+access+keys+for+system+use) instead of tying up an extra Stash account.

According to the Atlassian REST API docs ([REST Resources Provided By: Atlassian Stash SSH Plugin](https://developer.atlassian.com/static/rest/stash/3.10.0/stash-ssh-rest.html)), it seems they provide the ability to manage SSH keys for projects, repositories and individual users.

Oddly though, I could only find the ability to manage SSH keys for individual users in the [Java API](https://developer.atlassian.com/stash/docs/latest/reference/java-api.html) _(see: [com.atlassian.stash.ssh.api.SshKeyService](https://developer.atlassian.com/static/javadoc/stash/3.10.0/ssh/reference/com/atlassian/stash/ssh/api/SshKeyService.html))_.

Thanks,
-Alex

**Comment by terabyte** [comment]
@alexander-87 - you read my mind.  I actually have a support ticket open with atlassian as we speak asking how to use access keys.  I have two potential commits written, one which uses access keys and one which uses keys on the user, but both APIs seem to currently be private, causing the plugin to fail to install.

Access key version: 
https://github.com/terabyte/stashbot/commit/74ebbee142a6ecf52f25b43cbcf38e2ea57c677e

User key version:
https://github.com/terabyte/stashbot/commit/6a4900a5d1767ba9aca2426d0c8abddcffa45afd

The user key version depends upon SshKeyService, which is NOT in a package that contains ".internal", which makes me think it is not intended to be a private API but rather was an oversight, but hopefully they can shed some light on it.

**Comment by terabyte** [comment]
(if you want to clone one of those versions and see if you can make it work, you are welcome to)

(our last resort might be calling the rest API directly from the plugin in order to access the private APIs indirectly, but that causes LOTS of problems, like needing to store credentials for the REST API)

**Comment by alexander-87** [comment]
If the user has access to the **Stashbot CI Admin** screen, we can assume they're already logged in and have repository admin rights.

So, wouldn't the authentication for adding a SSH Service Account key through the REST API already be taken care of?

**Comment by alexander-87** [comment]
@bturner, are you aware of any plans to make the `SshKeyAccessService` available through the public API, or at least offer some insight as to why it isn't already?

Seems a bit odd that it's available through the REST API but not through the Java API.

**Comment by bturner** [comment]
@alexander-87 We're currently discussing it to decide the exact shape of what we want to publish. It may not be the entirety of what is currently the `SshKeyAccessService`, but at a minimum it would definitely be enough to cover the things that can be done via REST.

Bamboo's integration with Stash, since Bamboo is another Atlassian product, is built the opposite direction. You configure the repository as being Stash on the Bamboo side, and it uses REST to configure its access key on the Stash server.

I say that _not_ to say that we've kept the `SshKeyAccessService` private to prevent other CI servers from being able to have a good Stash integration. That's absolutely not the case. I only say it to explain why our focus was on the REST endpoints; it was what we needed at the time. [STASH-7526](https://jira.atlassian.com/browse/STASH-7526) will track us publishing the service. While I can't promise an exact release where we'll do it, I will say that we do not introduce new public APIs in patch releases, so 3.11.0 is the earliest possible version that would have it.

**Comment by terabyte** [comment]
@alexander-87 unfortunately, plugin code cannot make rest calls on behalf of the currently-logged-in-user, because there is no api to get a cookie or oauth token or anything.  Short of storing, prompting for, or otherwise gaining a username/password to make the rest call, there isn't really a way to do it.

In light of this, I am moving forward with the version that uses ssh keys attached to a particular user.  I will swap it to use access keys when the API is publicly available.  Because of the way I architected this, I think it will be pretty straightforward to do in the future.

I'll keep you guys updated with my progress.

Thanks!

**Comment by terabyte** [comment]
@bturner lemme just plug the idea of including com.atlassian.stash.ssh.utils.KeyUtils as well - looks like this class depends upon bouncycastle and is not exported in a way my plugin can see =(

EDIT: (or a util class with similar functionality.  working with keys is a bit janky right now)

**Comment by bturner** [comment]
While `KeyUtils` looks like it should be API (and really there's no reason for it not to be), the OSGi `Export-Package` directive for the SSH plugin is `com.atlassian.stash.ssh.api`, so `com.atlassian.stash.ssh.utils` isn't published.

Having an `api` package isn't really a Stash "thing"; our approach is to have an `internal` package for that which is not API, and anything not `internal` is API by default. The SSH plugin is from eaaaaaaaarly days though (Stash 1.1), so it was from a dark time before we really ironed out how we wanted to handle APIs. I'll see if I can't get it all changed up more completely to match the way our APIs are supposed to look.

**Comment by terabyte** [comment]
Ah, early days - makes sense.  FWIW, I am really impressed with how far stash has come, not only compared to the early days, but also compared to many of Atlassian's other earlier products (like Jira and Bamboo).  The quality of the codebase is obvious and it makes writing plugins way easier and more pleasant.

**Comment by bturner** [comment]
On a different note, I'd love to make some other suggestions about some of the ways this plugin integrates with Stash. Would anyone be interested in that?

For example, [TriggerJenkinsBuildHook](https://github.com/terabyte/stashbot/blob/master/src/main/java/com/palantir/stash/stashbot/hooks/TriggerJenkinsBuildHook.java#L121) really shouldn't need to use `GitScmCommandBuilder` to run `git branch`; [RefService.getBranches](https://developer.atlassian.com/static/javadoc/stash/3.10.0/api/reference/com/atlassian/stash/repository/RefService.html#getBranches%28com.atlassian.stash.repository.RepositoryBranchesRequest,%20com.atlassian.stash.util.PageRequest%29) (or [RepositoryMetadataService.getBranches](https://developer.atlassian.com/static/javadoc/stash/3.10.0/api/reference/com/atlassian/stash/repository/RepositoryMetadataService.html#getBranches%28com.atlassian.stash.repository.RepositoryBranchesRequest,%20com.atlassian.stash.util.PageRequest%29) if you want to be compatible with older versions of Stash) can do the same work in an SCM-agnostic way. Similar thing for the `git rev-list` usage; [CommitService.streamCommitsBetween](https://developer.atlassian.com/static/javadoc/stash/3.10.0/api/reference/com/atlassian/stash/commit/CommitService.html#streamCommitsBetween%28com.atlassian.stash.commit.CommitsBetweenRequest,%20com.atlassian.stash.commit.CommitCallback%29) (or [streamChangesetsBetween](https://developer.atlassian.com/static/javadoc/stash/3.10.0/api/reference/com/atlassian/stash/commit/CommitService.html#streamChangesetsBetween%28com.atlassian.stash.content.ChangesetsBetweenRequest,%20com.atlassian.stash.content.ChangesetCallback%29) if you want to be compatible with older versions of Stash) will allow you to get the same data much more simply. You can't specify a limit directly, but you can simply have your `CommitCallback.onCommit` implementation `return false` when you've handled as many commits as you want to handle.

**Comment by terabyte** [comment]
@bturner  - I am very interested in your suggestions and if you leave them here, I will eventually implement them.  Of course, if you prefer, you are welcome to make pull requests as well (if that is easier).

At the time I wrote the git branch stuff, either RefService.getBranches() wasn't available, or I couldn't find it, I most definitely considered shelling out to git a "last resort".

**Comment by terabyte** [comment]
(testing the GitScmCommandBuilder stuff is, of course, an unmitigated disaster, so the benefits are pretty clear for using services =)

**Comment by bturner** [comment]
@terabyte I wouldn't be surprised if you couldn't find it. Branch listing used to be done by the `RepositoryMetadataService`, which is not a very discoverable name for that functionality. That's why I renamed it to `RefService`, which I hoped people would look more closely at. Similar story for listing commits: Previously that was on the `HistoryService`, which I've renamed to the `CommitService`. They're separate from the `RepositoryService` to prevent that service from growing unmaintainably large. Between those two services and the `ContentService`, most plugins should be able to do the things they need to do without having to directly call the Git SCM.

If you need to list _all_ the branches, you can wrap the `getBranches()` call in a `PageProvider` and use `PagedIterable`. That way you get the data a page at a time under the hood, but to your code it's still presented like a single continuous iterator of `Branch`s.

The next tier after the `RefService` and the like is to use the `ScmService` to get one of Stash's `CommandFactory` types. These factories are what the various Stash services, like `RefService`, use to call the SCM. Our services don't expose the full range of functionality from the command factories because the SCM contract doesn't require it all.

Using the `ScmCommandBuilder`, or the `GitScmCommandBuilder`, is the lowest level. The Git SCM internally uses the `GitScmCommandBuilder` to implement the various `CommandFactory` types.

As for testing code that uses the command builder, you might take a look at Stash's `MockCallChainAnswer`. It automatically creates new mocks, but it captures them internally so that a subsequent call to the same method returns the same mock. You can create a mock `GitScmCommandBuilder` with that. Something like this:

``` java
MockCallChainAnswer callChain = new MockCallChainAnswer();
GitCommandBuilderFactory builderFactory = mock(GitCommandBuilderFactory.class, callChain);
```

Then if there's a specific step in the builder calls where you want to start controlling behavior, you just use `mockFor(Class)` on the `MockCallChainAnswer` to step in:

``` java
when(callChain.mockFor(Command.class).call()).thenThrow(NoSuchCommitException.class);
```

I'll add that the way the `GitScmCommandBuilder` is being used could be simplified further if your `CommandOutputHandler` implementations were specialized to the types they actually return. In [CommandOutputHandlerFactory](https://github.com/terabyte/stashbot/blob/master/src/main/java/com/palantir/stash/stashbot/outputhandler/CommandOutputHandlerFactory.java#L82), instead of `CommandOutputHandler<Object>`, use `CommandOutputHandler<List<String>>` (or `CommandOutputHandler<ImmutableList<String>>` if you prefer; I tend to use the interface instead of the implementation type).

When you `call()` a command, `call()` returns the result of `getOutput()` on the `CommandOutputHandler` you passed to `build(CommandOutputHandler)`. That's intended to allow the builders to be used in a very fluent way.

**Comment by terabyte** [comment]
@bturner regarding your suggestion: com.atlassian.stash:stash-build-integration should be set to "provided" and that nothing com.atlassian.stash should ever be anything but <scope>provided</scope>...

I tried that and it caused the following error:

```
[INFO] [talledLocalContainer] Caused by: java.lang.NoClassDefFoundError: com/atlassian/stash/internal/build/InternalBuildStatus
[INFO] [talledLocalContainer]   at com.palantir.stash.stashbot.servlet.BuildSuccessReportingServlet.getSuccessStatus(BuildSuccessReportingServlet.java:316) ~[na:na]
[INFO] [talledLocalContainer]   at com.palantir.stash.stashbot.servlet.BuildSuccessReportingServlet.doGet(BuildSuccessReportingServlet.java:209) ~[na:na]
[INFO] [talledLocalContainer]   ... 19 common frames omitted
```

Does this mean there is a bug in that bundle and it is not exporting the things it depends upon properly?

EDIT:  oh, grepping my code base, I see that I actually use InternalBuildStatus object directly... presumably this is the problem, it is clearly an internal API...  maybe I need to re-examine how to do this using the public APIs...

**Comment by terabyte** [comment]
I have my "first fully working version" done now, on the branch feature/ssh-creds-by-user.  I'm leaving this PR open so I can finish implementing @bturner's other most-excellent suggestions.

**Comment by bturner** [comment]
@terabyte It looks like the build status integration is done in such a way that Jenkins calls back into a servlet in your plugin, rather than just posting to the REST endpoint for `BuildStatus` that we've already built. If the Jenkins side can be coerced to produce the right JSON shape, it could just post directly to the [BuildStatusResource](https://developer.atlassian.com/static/rest/stash/3.10.2/stash-build-integration-rest.html#idp764528) to add build results. Since Jenkins can't be AppLinked to Stash, the Jenkins side would need to post back to Stash with basic authentication for the request to be accepted.

If that's not possible, for the moment what I'd suggest is just implementing your own trivial `BuildStatus` type, rather than using our internal one. That's going to give you the best compatibility without trying to dip below our API. For our 4.0 release I'll investigate making what is currently `InternalBuildStatus` available for plugin developers (but it's unlikely that one will change prior to 4.0).

Keep bringing them up as you find more issues like this! I appreciate your feedback.

**Comment by terabyte** [comment]
@btuner - cool, that's pretty much what I thought you'd say - I will definitely keep them coming - I am glad to hear my feedback is helpful!

**Comment by terabyte** [comment]
@alexander-87 @bturner so, I have munged a few things and taken the version of stashbot that we are using in production at my current company, and pushed it to master.  Moving forward, the "stable" version of stash is going to be the "prod" branch, and mainline development will occur on "master".  The other forks will be maintained in archived branches.  Just wanted to let you guys know.

Thanks!

**Pull request merged**
