### PR TITLE
use pull-request refspec in verify_pr job

### PR DESCRIPTION
**Pull request by memory**
This addresses issue #26 in terabyte/stashbot

Note that this only fixes the backport branch! :)

### CODE REVIEW

**Comment by terabyte** [comment]
This doesn't quite work - repro steps:
1. ./ibin/invoke-sdk.sh clean test stash:debug
2. log in as "admin:admin", go to admin's profile, remove the ssh key, go to jenkins admin settings, set jenkins user to "user". The ssh key will be added to that user automatically.
3. create a PR in rep_1 from "basic_branching" to master - it succeeds
4. fork the repo into admin's project (which "user" won't be able to read)
5. create a PR from admin's "basic_branching" branch into the parent project, build fails.

**Comment by terabyte** [comment]
I noticed that when I examined the job in jenkins, the "refspec" field was empty, so it was like the newly desired refspec was missing.

**Comment by memory** [comment]
Ho ho ho.  Turns out I did not do sufficient grepping, and there are two possible places in these templates where the git plugin could be invoked, depending on what kind of auth strategy you're using.

**Comment by memory** [comment]
(Also added the refspec to both verify builds.)

**Pull request merged**
