### PR TITLE
abuse javascript to pass buildref in from trigger links

### PR DESCRIPTION
**Pull request by memory**
It's not pretty, but it appears to work.

### CODE REVIEW

**Comment by terabyte** [comment]
This actually looks pretty likely to continue to work in bitbucket as well, though testing will be needed =)

**Comment by memory** [comment]
poke

**Comment by terabyte** [comment]
Repeated here for posterity/hilarity:

```
< cmyers> let us join hands and hearts in our ardent hope that atlassian never renames the "repository-layout-revision-selector" element, or alters its contents.
```

**Comment by terabyte** [comment]
This was reverted by a force push shortly after merging, because...reasons.  So this PR is a lie.

**Pull request merged**
